name = "0x-shopify-api"
main = "src/index.ts"
compatibility_date = "2026-10-04"

[vars]
CORS_ORIGINS = "http://localhost:5173"
SHOPIFY_API_VERSION = "2026-10"

[[d1_databases]]
binding = "DB"
database_name = "0x-shopify-demo"
database_id = "6bf34a0e-dc2a-4a2a-afee-f2892ced45a0"
migrations_dir = "migrations"

[triggers]
crons = ["*/5 * * * *"]

[env.production]
name = "0x-shopify-api"

[env.production.vars]
CORS_ORIGINS = "https://0x-shopify-storefront-public.vercel.app"
SHOPIFY_API_VERSION = "2026-10"

[[env.production.d1_databases]]
binding = "DB"
database_name = "0x-shopify-demo"
database_id = "6bf34a0e-dc2a-4a2a-afee-f2892ced45a0"
